apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: bidip-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: projectred521/flask-ip:v0.1.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
